version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: search-parser-nginx
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx/nginx.conf.development:/etc/nginx/conf.d/nginx.conf
    restart: always
    depends_on:
      - client
      - server
    networks:
      - search-parser-network

  server:
    container_name: search-parser-server
    restart: always
    build:
      target: development
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/src:/app/src
    depends_on:
      - db
    networks:
      - search-parser-network

  client:
    container_name: search-parser-client
    restart: always
    build:
      target: development
      context: ./client
      dockerfile: Dockerfile
    environment:
      - WDS_SOCKET_PORT=0
    stdin_open: true
    tty: true
    volumes:
      - ./client/src:/app/src
    networks:
      - search-parser-network

  db:
    container_name: search-parser-db
    image: postgres:14-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgre:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - search-parser-network

  pgadmin:
    container_name: search-parser-pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - search-parser-network

networks:
  search-parser-network:
    driver: bridge
    name: search-parser-network